name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    name: Build & Test (C++23)
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - name: Install
        run: |
          sudo apt-get update -q
          sudo apt-get install -y g++-13

      - name: Compile and test (C++23)
        run: |
          g++-13 -std=c++23 -O2 -Wall -Wextra \
            -I include \
            tests/*.cpp \
            -o test_runner
          ./test_runner
